channels:
- conda-forge
dependencies:
# - jupyterlab=1.0.4
- python=3.7
- nodejs
- ipython
- ipywidgets=7.5.1
- notebook
- ipykernel
- nglview=2.7
- rdkit::rdkit
- pip:
    - pytraj
    - ipython_blocking
    - moviepy
